export const USER_UPLOAD_IMG_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_UPLOAD_IMG_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_UPLOAD_IMG_FAIL = 'USER_REGISTER_FAIL';

export const IDENTIFICATION_REQUEST = "IDENTIFICATION_REQUEST"
export const IDENTIFICATION_FAIL = "IDENTIFICATION_FAIL"
export const IDENTIFICATION_SUCCESS = "IDENTIFICATION_SUCCESS"

export const SHOW_RESULTS_REQUEST = "SHOW_RESULTS_REQUEST"
export const SHOW_RESULTS_FAIL = "SHOW_RESULTS_FAIL"
export const SHOW_RESULTS_SUCCESS = "SHOW_RESULTS_SUCCESS"

export const CLEAR_ERROR_MSG = "CLEAR_ERROR_MSG"


