// export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
// export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
// export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
//
// // export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
// // export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
// // export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';


export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_FAVORITE_REQUEST = 'USER_FAVORITE_REQUEST';
export const PRODUCT_ADD_FAVORITE_SUCCESS = 'USER_ADD_FAVORITE_SUCCESS';
export const PRODUCT_REM_FAVORITE_SUCCESS = 'USER_REM_FAVORITE_SUCCESS';
export const FAVORITE_LIST_REQUEST = 'USER_LIST_REQUEST';
export const FAVORITE_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const PRODUCT_LIST_DELETE = 'PRODUCT_LIST_DELETE';
export const EDIT_WARNING_LIGHT = 'DELETE_WARNING_LIGHT';
export const PRODUCT_LIST_ADD = 'PRODUCT_LIST_ADD';
